# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# https://go.microsoft.com/fwlink/?LinkId=248929

# Builds the SimpleMath module for Windows Subsystem for Linux (WSL)

schedules:
  - cron: "30 3 * * *"
    displayName: 'Nightly build'
    branches:
      include:
        - main

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '.azuredevops/pipelines/DirectXTK-GitHub-WSL-13.yml'
      - CMake*
      - build/*.cmake
      - build/*.in
      - Inc\SimpleMath.*
      - Src\SimpleMath.*

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
      trigger: none
    - repository: dxHeadersRepo
      name: Microsoft/DirectX-Headers
      type: github
      endpoint: microsoft
      ref: refs/heads/main
    - repository: dxMathRepo
      name: Microsoft/DirectXMath
      type: github
      endpoint: microsoft
      ref: refs/heads/main
    - repository: testRepo
      name: walbourn/directxtktest
      type: github
      endpoint: microsoft
      ref: refs/heads/main

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: ubuntu-24.04

variables:
  Codeql.Enabled: false
  LOCAL_PKG_DIR: '$(Agent.BuildDirectory)/install/'
  SAL_URL: https://raw.githubusercontent.com/dotnet/runtime/v8.0.1/src/coreclr/pal/inc/rt/sal.h
  SAL_HASH: 0f5a80b97564217db2ba3e4624cc9eb308e19cc9911dae21d983c4ab37003f4756473297ba81b386c498514cedc1ef5a3553d7002edc09aeb6a1335df973095f

jobs:
  - job: BUILD_SIMPLEMATH
    displayName: SimpleMath
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 1
    steps:
      - checkout: self
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's'
      - checkout: dxHeadersRepo
        displayName: Fetch DirectX-Headers
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's/DirectX-Headers'
      - checkout: dxMathRepo
        displayName: Fetch DirectX-Math
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's/DirectXMath'
      - checkout: testRepo
        displayName: Fetch Tests
        clean: true
        fetchTags: false
        fetchDepth: 1
        path: 's/Tests'
      - task: CMake@1
        displayName: CMake DirectX-Headers
        inputs:
          cwd: DirectX-Headers
          cmakeArgs: >
            . -DDXHEADERS_BUILD_TEST=OFF -DDXHEADERS_BUILD_GOOGLE_TEST=OFF
            -DCMAKE_INSTALL_PREFIX=$(LOCAL_PKG_DIR)
      - task: CMake@1
        displayName: CMake DirectX-Headers (Build)
        inputs:
          cwd: DirectX-Headers
          cmakeArgs: --build . -v
      - task: CMake@1
        displayName: CMake DirectX-Headers (Install)
        inputs:
          cwd: DirectX-Headers
          cmakeArgs: --install .
      - task: CMake@1
        displayName: CMake DirectXMath
        inputs:
          cwd: DirectXMath
          cmakeArgs: . -DCMAKE_INSTALL_PREFIX=$(LOCAL_PKG_DIR)
      - task: CMake@1
        displayName: CMake DirectXMath (Build)
        inputs:
          cwd: DirectXMath
          cmakeArgs: --build . -v
      - task: CMake@1
        displayName: CMake DirectXMath (Install)
        inputs:
          cwd: DirectXMath
          cmakeArgs: --install .
      - task: PowerShell@2
        displayName: Fetch SAL.H
        inputs:
          targetType: inline
          script: |
            $ProgressPreference = 'SilentlyContinue'
            Invoke-WebRequest -Uri "$(SAL_URL)" -OutFile $(LOCAL_PKG_DIR)/include/sal.h
            $fileHash = Get-FileHash -Algorithm SHA512 $(LOCAL_PKG_DIR)/include/sal.h | ForEach { $_.Hash} | Out-String
            $filehash = $fileHash.Trim()
            Write-Host "##[debug]SHA512: " $filehash
            if ($fileHash -ne "$(SAL_HASH)") {
                Write-Error -Message "##[error]Computed hash does not match!" -ErrorAction Stop
            }

      - task: CMake@1
        displayName: CMake SimpleMath (Config) dbg
        inputs:
          cwd: Tests/SimpleMathTest
          cmakeArgs: >
            -B out -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_PREFIX_PATH=$(LOCAL_PKG_DIR)/share;$(LOCAL_PKG_DIR)/cmake
      - task: CMake@1
        displayName: CMake SimpleMath (Build) dbg
        inputs:
          cwd: Tests/SimpleMathTest
          cmakeArgs: --build out -v
      - task: CMake@1
        displayName: CMake SimpleMath (Config) rel
        inputs:
          cwd: Tests/SimpleMathTest
          cmakeArgs: >
            -B out2 -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_PREFIX_PATH=$(LOCAL_PKG_DIR)/share;$(LOCAL_PKG_DIR)/cmake
      - task: CMake@1
        displayName: CMake SimpleMath (Build) rel
        inputs:
          cwd: Tests/SimpleMathTest
          cmakeArgs: --build out2 -v
      - task: CmdLine@2
        displayName: Run tests dbg
        inputs:
          script: ./out/bin/simplemathtest
          workingDirectory: Tests/SimpleMathTest
      - task: CmdLine@2
        # This is disabled due to a failure in Vector3 reflect and Viewport unproject in release mode.
        displayName: Run tests rel
        enabled: false
        inputs:
          script: ./out2/bin/simplemathtest
          workingDirectory: Tests/SimpleMathTest
