# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkId=248929

# Builds the library for Windows Desktop and UWP.

schedules:
- cron: "0 2 * * *"
  displayName: 'Nightly build'
  branches:
    include:
    - main

# GitHub Actions handles MSBuild for CI/PR
trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - '.azuredevops/pipelines/DirectXTK-GitHub.yml'
    - Src/Shaders/CompileShaders.cmd

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: windows-2019

variables:
- group: dxtk-shared-variables
- name: Codeql.Enabled
  value: false
- name: GUID_FEED
  value: $(ADOFeedGUID)

jobs:
- job: DESKTOP_BUILD
  displayName: 'Win32 Desktop'
  timeoutInMinutes: 120
  cancelTimeoutInMinutes: 1
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019.sln 32dbg
    inputs:
      solution: DirectXTK_Desktop_2019.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x86
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019.sln 32rel
    inputs:
      solution: DirectXTK_Desktop_2019.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x86
      configuration: Release
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019.sln 64dbg
    inputs:
      solution: DirectXTK_Desktop_2019.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x64
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019.sln 64rel
    inputs:
      solution: DirectXTK_Desktop_2019.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x64
      configuration: Release
  - task: CmdLine@2
    displayName: 'Reclaim diskspace'
    inputs:
      script: del *.pch /s
      workingDirectory: $(Build.SourcesDirectory)
      failOnStderr: false
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019.sln managed dbg
    inputs:
      solution: DirectXTK_Desktop_2019.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: Mixed Platforms
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019.sln managed rel
    inputs:
      solution: DirectXTK_Desktop_2019.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: Mixed Platforms
      configuration: Release
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019_Win10.sln 32dbg
    inputs:
      solution: DirectXTK_Desktop_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x86
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019_Win10.sln 32rel
    inputs:
      solution: DirectXTK_Desktop_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x86
      configuration: Release
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019_Win10.sln 64dbg
    inputs:
      solution: DirectXTK_Desktop_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x64
      configuration: Debug
  - task: VSBuild@1
    displayName: Build solution DirectXTK_Desktop_2019_Win10.sln 64rel
    inputs:
      solution: DirectXTK_Desktop_2019_Win10.sln
      msbuildArgs: /p:PreferredToolArchitecture=x64
      platform: x64
      configuration: Release
