# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ignore-from-file: .gitignore

extends: default

rules:
  truthy:
    check-keys: false
  document-start: disable
  line-length:
    max: 160
  comments:
    min-spaces-from-content: 1
  new-lines:
    type: dos
