# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkId=248929

name: MSBuild (UWP Tests)

on:
  push:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.github/*.md'
      - '.nuget/*'
      - build/*
  pull_request:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.github/*.md'
      - '.nuget/*'
      - build/*

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    strategy:
      fail-fast: false

      matrix:
        build_type: [Debug, Release]
        platform: [x86, x64, ARM64]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Clone test repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: walbourn/directxtktest
          path: Tests
          ref: main

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
        with:
          msbuild-architecture: x64

      - name: 'Build (UWP)'
        working-directory: ${{ github.workspace }}/Tests
        run: >
          msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }}
          /T:Build /p:AppxPackage=false
          DirectXTK_Tests_Windows10.sln
